export { default as Header } from "./Header"
export { default as Hero } from "./Hero"
export { default as About } from "./About"
export { default as Resume } from "./Resume"
export { default as Portfolio } from "./Portfolio"
export { default as Blogs } from "./Blogs"
export { default as Contact } from "./Contact"
export { default as Footer } from "./Footer"